#!/bin/bash
set -e

usage() {
   echo "Usage: $0 [options]"
   echo "  -h, -?         display this help screen"
}

while getopts "h?j:" arg; do
   case "$arg" in
      h|\?)
         usage
         exit 0
      ;;
      *)
         usage >&2
         exit 1
      ;;
   esac
done
shift $((OPTIND -1))

sed -i -e 's@wget ${EIGEN_URL} --no-check-certificate@cp /app/data/eigen-3.3.7.tar.bz2 .@' bootstrap.sh
./bootstrap.sh 
